### ISSUE TITLE
Resource ID Reference

### ISSUE THREAD

**Issue by dwhofer** [wearearchitect/sharepoint-oauth-app-client#1]
Please add a reference to where we can find the Resource ID somewhere in the documentation.

Thank You.

**Comment by quetzyg** [comment]
This one's for you @Estro!

**Comment by Estro** [comment]
If using SharePoint Online, goto /_layouts/15/appprincipals.aspx?Scope=Web and you can get it from the Microsoft.Sharepoint App Identifier column. It is the GUID after the @ symbol.

**Comment by dwhofer** [comment]
Thank You!  I am using a Hosted Sharepoint Service.  When I use that URL, it takes me to a Site App Permissions page and the page displays, "There are no apps having explicit access to the site."   I am trying to use PHP to access existing Sharepoint objects (custom lists) via the REST APIs.

**Comment by dwhofer** [comment]
I figured this Issue out.  Thanks!  I did not register my app properly using _layouts/15/AppInv.aspx.  This gave me the guid that I needed and now my app shows up under _layouts/15/appprincipals.aspx
