### ISSUE TITLE
Unknown SSL protocol error in connection to accounts.accesscontrol.windows.net:443

### ISSUE THREAD

**Issue by dwhofer** [wearearchitect/sharepoint-oauth-app-client#2]
Hello again,

I am getting much closer, but now I am getting this error: 
Unable to get the access token from ACS: Unknown SSL protocol error in connection to accounts.accesscontrol.windows.net:443

I am using the most recent version of openssl on Ubuntu and have change the curl options to v3.

Here is the code that is throwing this error.  I've scrambled the IDs.

```
       $acs_server = 'https://accounts.accesscontrol.windows.net/tokens/OAuth/2';
    $postdata = array(
        'grant_type' => 'refresh_token',
        'client_id' => 'xxxxxxxx-a5e6-xxxx-bx88-xxxxxca98d47',
        'client_secret' => 'ADzDP7m3xxx1lAnwJqi432gnSKgtrWHNg321DiMxyzw@',
        'refresh_token' => $msg->refreshtoken,
        'resource' => 'xxxxxxxx-840f-xxxx-826f-xxxxe977xyz1' 
    );      
    $querydata = http_build_query($postdata);

    // Add additional headers
    $opts = array(
        'Content-type: application/x-www-form-urlencoded', 
        'Expect: 100-continue'
    );

    // Request the token from ACS (manually build the POST request)
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $acs_server);
    curl_setopt($ch, CURLOPT_HTTPHEADER, $opts);
    curl_setopt($ch, CURLOPT_HEADER, 0);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $querydata);
    curl_setopt ($ch, CURLOPT_SSL_VERIFYHOST, 0);
    curl_setopt ($ch, CURLOPT_SSL_VERIFYPEER, 0);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_SSLVERSION,3);

    $result = curl_exec($ch);
```

Sorry to be a PIA on this, I am very close and have tried everything that I can think of to get this connection to work.   The $msg->refreshtoken does not have a value.

Thank YOu.

**Comment by quetzyg** [comment]
Please, submit bug reports related to the library, not for code you've written.

**Comment by quetzyg** [comment]
The [troubleshooting](https://github.com/wearearchitect/sharepoint-oauth-app-client/blob/master/docs/Troubleshooting.md) should have you covered, anyway.
