### ISSUE TITLE
Don't understand on what site settings to use

### ISSUE THREAD

**Issue by mediamonks-robert** [wearearchitect/sharepoint-oauth-app-client#5]
Currently I received these details:
- Client ID - a GUID
- Client Secret - a base64? encoded string
- Resource - a string with format <Client ID>@<site>@<another GUID>

When trying to connect using these details I get this error:

AADSTS90019: Unable to determine the tenant identifier from the request. Client ID '<Client ID>' does not specify a tenant realm.

When I modify the client_id to be like the resource I get:

AADSTS70001: Application with identifier <Client ID>/<domain>' was not found in the directory <resource>

I started reading the page about the bearer (https://github.com/wearearchitect/sharepoint-oauth-app-client/blob/master/docs/Credentials.md#odata-client-webservice-data) and I think it does not clarify which values should be swapped with the site details I currently have. Can you provide me this information so I can get the bearer realm and use your library? Thanks :)

**Comment by quetzyg** [comment]
Hi there @mediamonks-robert!

The [credential instructions](https://github.com/wearearchitect/sharepoint-oauth-app-client/blob/master/docs/Credentials.md#odata-client-webservice-data) that we got in the library docs are a stripped down version of what you might find [here](http://spshell.blogspot.in/2015/03/sharepoint-online-o365-oauth.html), for example.

I'm not sure about the `does not specify a tenant realm.` error, though.

@Estro should know better than me.

**Comment by mediamonks-robert** [comment]
Thanks for your answer but unfortunately I can't get it to work. For some reason I don't have enough permissions to take all the required steps.

**Comment by Estro** [comment]
You will need site collection admin permissions to the site collection to register the app.

**Comment by mediamonks-robert** [comment]
My issue seems to be solved and when reading it back it makes sense how it is described in the credential instructions. Because I did not make the app myself it was not clear that "app_domain" is filled in by the user who creates the app. After getting the bearer realm and getting the app domain from the consultant who created the app I was able to login successfully.

**Comment by quetzyg** [comment]
Cool, nice it worked out OK for you @mediamonks-robert.

**Comment by mediamonks-robert** [comment]
Forgot to say: thanks for the library and the quick support :+1:
